# Indexación de un solo elemento

In [1]:
import numpy as np

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Extracción de elementos de forma ascendente

In [2]:
x[2]

2

# Extracción de elementos de forma descendente

In [3]:
x[-2]

8

# Conversión del arreglo a formato bidimensional

In [4]:
x.shape = (2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Extracción del elemento con índice 1 en renglón e índice 3 en columna

In [5]:
x[1,3]

8

# Alternativa de extracción del elemento con índice 1 en renglón e índice 3 en columna

In [6]:
x[1][3]

8

# Extracción del elemento con índice 1 en renglón y primer elemento en forma descendente

In [7]:
x[1,-1]    

9

# Extracción del renglón completo con índice 0 (al no especificar índice de columna)

In [8]:
x[0]

array([0, 1, 2, 3, 4])

# Cortes en arreglos

In [9]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
x[1:7:2]    #--------------------------------> Formato:   "start : stop: step"

array([1, 3, 5])

# Corte del arreglo de adelante hacia atrás, considerando dos elementos.

In [10]:
x[-2:10]

array([8, 9])

# Corte del arreglo de adelante hacia atrás, iniciando tres posiciones a partir del final y retrocediendo hasta tener como límite el número 3

In [11]:
x[-3:3:-1]

array([7, 6, 5, 4])

# Definición de un nuevo arreglo

# Creación de un arreglo en forma descendente  (del 10 al 1(sin incluirlo)) con decrementos de

In [12]:
x = np.arange(10, 1, -1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

# Extracción de elementos específicos del arreglo

# Extracción de elementos con índices  3, 3, 1, 8

In [13]:
x[np.array([3, 3, 1, 8])]      #----------------------->   array([10,  9,  8,  7,  6,  5,  4,  3,  2])

array([7, 7, 9, 2])

# Extracción de elementos con índice 3,3, -3 (descendente) y 8

In [14]:
x[np.array([3, 3, -3, 8])] 

array([7, 7, 4, 2])

# Extracción basada en pares

In [15]:
y = np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

# Extracción de coordenadas (0,0), (2,1) y (4,2)

In [17]:
y[np.array([0, 2, 4]), np.array([0, 1, 2])]

array([ 0, 15, 30])

# Unión de arreglos

# Concatenación de vectores

In [18]:
arr = np.concatenate(([1, 2, 3],[4,5,6]))
arr

array([1, 2, 3, 4, 5, 6])

# Apilado vertical de vectores

In [19]:
np.stack(([1,2,3], [4,5,6]))

array([[1, 2, 3],
       [4, 5, 6]])

# Concatenación de matrices

In [20]:
mat_1 = np.array([[1, 2, 3],[4, 5, 6]])
mat_2 = np.array([[1, 1, 1],[2, 2, 2]])
np.concatenate((mat_1, mat_2), axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [2, 2, 2]])

In [21]:
np.concatenate((mat_1, mat_2), axis = 1)

array([[1, 2, 3, 1, 1, 1],
       [4, 5, 6, 2, 2, 2]])

In [22]:
np.concatenate((mat_1, mat_2), axis = None)

array([1, 2, 3, 4, 5, 6, 1, 1, 1, 2, 2, 2])