# NumPy en el ecosistema de Python

In [ ]:
--El elemento primordial de trabajo en NumPy es el arreglo.

In [1]:
import numpy as np

# Creación de un arreglo a partir de una lista

In [2]:
lista1 = [1, 2, 3, 4, 5]
arreglo1 = np.array(lista1)
arreglo1

array([1, 2, 3, 4, 5])

In [3]:
type(arreglo1)

numpy.ndarray

# Creación de un arreglo a partir de una lista de listas

In [4]:
lista2 = [[1,2,3], 
          [4,5,6],
          [7,8,9]]
arreglo2 = np.array(lista2)
arreglo2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Las listas pueden contener diversos tipos de datos

In [5]:
lista = ["a", True, 1]
lista

['a', True, 1]

# Los arreglos solo pueden tener un mismo tipo de datos

# Usan menos espacio en memoria

In [6]:
arreglo = np.array(lista)
arreglo    #-----------------------------------> solo se almacenan textos

array(['a', 'True', '1'], dtype='<U11')

# Creación de arreglos con ceros

In [7]:
arreglo3 = np.zeros((5,4))
arreglo3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Creación de arreglos con números aleatorios uniformes entre 0 y 1

In [8]:
np.random.random((3,2))

array([[0.19709758, 0.42723501],
       [0.87927268, 0.3436093 ],
       [0.44411397, 0.80956288]])

# Creación de arreglos en un rango

In [9]:
np.arange(-2,7)

array([-2, -1,  0,  1,  2,  3,  4,  5,  6])

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

# Creación de un arreglo con NumPy

# ejercicio:   Mediante el uso de la librería NumPy desarrolle un código en Python que sea capaz de crear el arreglo Tri-dimensional siguiente:

In [15]:
arreglo1 = np.array([[1,2],
                     [5,7]])
arreglo2 = np.array([[8,9],
                     [5,7]]) 
arreglo3 = np.array([[1,2],
                     [5,7]]) 

arreglo_3D = np.array([arreglo1, arreglo2, arreglo3])
arreglo_3D

array([[[1, 2],
        [5, 7]],

       [[8, 9],
        [5, 7]],

       [[1, 2],
        [5, 7]]])

In [16]:
arreglo_3D = np.array([arreglo1, arreglo2, arreglo3])
arreglo_3D

array([[[1, 2],
        [5, 7]],

       [[8, 9],
        [5, 7]],

       [[1, 2],
        [5, 7]]])

In [17]:
arreglo3 = np.zeros((5,4))
arreglo3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
arreglo3.shape   #-----------------------> nos dice el tamaño del arreglo.

(5, 4)

# conversión de un arreglo multi-dimensional a uni-dimensional

In [19]:
lista2 = [[1,2,3],
          [4,5,6],
          [7,8,9]]

arreglo2 = np.array(lista2)
arreglo2  

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arreglo2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# cambio de dimensión de un arreglo

In [21]:
arreglo = np.array([[1,2],
                    [3,4],
                    [5,6]])

arreglo.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

# ejemplo de ERROR  al momento de cambiar la dimensión

In [22]:
arreglo.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [ ]:
--Una matriz tiene 2 dimensiones(es un arreglo BIDIMENSIONAL).
--Un TENSOR tiene 3 o más dimensiones.

# El atributo dtype

In [ ]:
determina que tipo de arreglo vamos a guardar

In [23]:
np.array([1.25, 2.43, 200.88]).dtype

dtype('float64')

In [24]:
arreglo_int = np.array([[1,2,3], [4,5,6]])
arreglo_int.dtype

dtype('int32')

In [25]:
arreglo_string = np.array(["Introducción", "a", "la", "programación"])
arreglo_string.dtype

dtype('<U12')

# Uso de dtype como argumento

In [26]:
arreglo = np.array([1.25, 2.43, 200.88], dtype = np.float32)     #------->  Mismo arreglo de arriba
arreglo.dtype                                                    #-----> aloja menos memoria

dtype('float32')

# Cambio de tipo de arreglo 

In [27]:
arreglo_booleano = np.array([[True, False]], dtype = np.bool_)
arreglo_booleano.dtype

dtype('bool')

In [28]:
arreglo = arreglo_booleano.astype(np.int32)
arreglo

array([[1, 0]])

# Homologación del tipo por jerarquía

In [29]:
np.array([0, 50, 50.8]).dtype

dtype('float64')

In [30]:
np.array([False, 42])

array([ 0, 42])

# Operaciones con arreglos en NumPy

# ejercicio.-  Considere los datos siguientes:  que corresponden a estadísticas de accidentes en una empresa para tres áreas durante cuatro años:

In [ ]:
import numpy as np
accidentes = np.array([[0,1,1],
                      [1,0,1],
                      [1,3,2],
                      [2,2,0]])


# a) determine el número total de accidentes durante los cuatro años:

In [2]:
import numpy as np
accidentes = np.array([[0,1,1],
                      [1,0,1],
                      [1,3,2],
                      [2,2,0]])

accidentes.sum()

14

# b) determine el número total de accidentes por área (por columna)

In [3]:
accid_areas = accidentes.sum(axis = 0)
accid_areas

array([4, 6, 4])

In [4]:
print("Los accidentes del área 1: ", accid_areas[0])
print("Los accidentes del área 2: ", accid_areas[1])
print("Los accidentes del área 3: ", accid_areas[2])

Los accidentes del área 1:  4
Los accidentes del área 2:  6
Los accidentes del área 3:  4


# c) determine el número total de accidentes por año (por renglón)

In [5]:
accid_anios = accidentes.sum(axis = 1)
accid_anios

array([2, 2, 6, 4])

# Conservación de dimensiones

In [6]:
accid_anios = accidentes.sum(axis = 1, keepdims = True)
accid_anios

array([[2],
       [2],
       [6],
       [4]])

In [8]:
print("Los accidentes del año 1: ", accid_anios[0])
print("Los accidentes del año 2: ", accid_anios[1])
print("Los accidentes del año 3: ", accid_anios[2])
print("Los accidentes del año 4: ", accid_anios[3])

Los accidentes del año 1:  [2]
Los accidentes del año 2:  [2]
Los accidentes del año 3:  [6]
Los accidentes del año 4:  [4]


# d) determine el número máximo y mínimo de accidentes por área y año

In [9]:
maximo = accidentes.max()
minimo = accidentes.min()

print(f"Máximo de accidentes: {maximo}")
print(f"Mínimo de accidentes: {minimo}")

Máximo de accidentes: 3
Mínimo de accidentes: 0


# e) determine el número promedio de accidentes por área y año

In [10]:
promedio = accidentes.mean()
print(f"Promedio de accidentes: {promedio}")

Promedio de accidentes: 1.1666666666666667


# Operaciones vectorizadas

In [ ]:
--Incluyen funciones tales como: "sum", "min" y "max"
--Permiten realizar operaciones más rápidamente (en comparación a su equivalente mediante ciclos en Python)  
--Están soportadas por el lenguaje C.

# ejercicio:   Determine la suma descrita en la imágen de abajo mediante:

# a)Un ciclo en Python

# b) Una función vectorizada de NumPy

In [11]:
arreglo = np.array([[1,2,3],
                    [4,5,6]])

dimensiones = arreglo.shape

print(dimensiones[0])    #------->Renglones
print(dimensiones[1])    #------->Columnas
print(arreglo[0][0])

2
3
1


# Inciso a)

In [12]:
import time
inicio = time.time()

arreglo_final = np.zeros((2,3))
for renglon in range(dimensiones[0]):
    for columna in range(dimensiones[1]):
        arreglo_final[renglon][columna] = arreglo_final[renglon][columna] + 3
        
print(arreglo_final)

fin = time.time()
print("Tiempo total de ejecución (segs.)", fin - inicio)

[[3. 3. 3.]
 [3. 3. 3.]]
Tiempo total de ejecución (segs.) 0.0


In [13]:
import time
inicio = time.time()

arreglo_final = np.zeros((2,3))
for renglon in range(dimensiones[0]):
    for columna in range(dimensiones[1]):
        arreglo_final[renglon][columna] = arreglo[renglon][columna] + 3
        
print(arreglo_final)

fin = time.time()
print("Tiempo total de ejecución (segs.)", fin - inicio)

[[4. 5. 6.]
 [7. 8. 9.]]
Tiempo total de ejecución (segs.) 0.0009386539459228516


# inciso b

In [14]:
import time
inicio = time.time()

arreglo_final = arreglo + 3
print(arreglo_final)

fin = time.time()
print("Tiempo total de ejecución (segs.)", fin - inicio)

[[4 5 6]
 [7 8 9]]
Tiempo total de ejecución (segs.) 0.0010077953338623047


# Transmisión en NumPy ("Broadcasting")

# Reglas de compatibilidad para operaciones entre arreglos:

In [ ]:
--Uno de ellos tiene longitud de 1
--Son de longitudes iguales

# Multiplicación por un escalar

In [15]:
arreglo_prod = arreglo * 3 
arreglo_prod

array([[ 3,  6,  9],
       [12, 15, 18]])

# Adición de dos arreglos

In [16]:
arreglo1 = np.array([[1,2,3],
                     [4,5,6]])

arreglo2 = np.array([[7,8,9],
                     [10,11,12]])

arreglo3 = arreglo1 + arreglo2
arreglo3

array([[ 8, 10, 12],
       [14, 16, 18]])

# Evaluación de condiciones

In [17]:
arreglo1 =np.array([[1,2,3],
                    [4,5,6]])

arreglo1 > 2

array([[False, False,  True],
       [ True,  True,  True]])

# Las funciones de Python no están vectorizadas de origen

In [18]:
arreglo = np.array(["NumPy", "maneja", "vectorización"])
len(arreglo) > 5                            #----------------->

False

# Transformación para vectorización de la función "len"

In [19]:
len_vectorizada = np.vectorize(len)
len_vectorizada(arreglo) > 2

array([ True,  True,  True])

In [20]:
len_vectorizada = np.vectorize(len)
len_vectorizada(arreglo) > 5

array([False,  True,  True])

# Broadcasting de renglones

In [21]:
arreglo = np.arange(10).reshape((2,5))
arreglo

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
arreglo + np.array([0,1,2,3,4])

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

# Broadcasting de columnas

In [23]:
arreglo = np.arange(10).reshape((2,5))
arreglo + np.array([0,1]).reshape((2,1))

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

# Error cuando no se cumplen las reglas de compatibilidad

In [24]:
arreglo + np.array([0,1])

ValueError: operands could not be broadcast together with shapes (2,5) (2,) 

# Volteo a un arreglo

In [25]:
arreglo = np.array([[1.1, 1.2, 1.3],
                    [2.1, 2.2, 2.3],
                    [4.1, 4.2, 4.3]])

np.flip(arreglo)

array([[4.3, 4.2, 4.1],
       [2.3, 2.2, 2.1],
       [1.3, 1.2, 1.1]])

# Transposición de un arreglo

In [26]:
arreglo = np.array([[1.1, 1.2, 1.3],
                    [2.1, 2.2, 2.3],
                    [4.1, 4.2, 4.3]])

np.transpose(arreglo)

array([[1.1, 2.1, 4.1],
       [1.2, 2.2, 4.2],
       [1.3, 2.3, 4.3]])

# ejercicio 1

In [27]:
np.array([[1,2], [3,4]]) * np.array([[5], [10]])

array([[ 5, 10],
       [30, 40]])

# ejercicio 2

In [29]:
np.array([[1,2], [3,4]]) - np.array([[5, 10]])

array([[-4, -8],
       [-2, -6]])