In [1]:
from sklearn.preprocessing import normalize
import numpy as np

# Supongamos que data es una matriz NumPy con valores numéricos
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Normalizar los datos
data_scaled = normalize(data)

# Imprimir los datos normalizados
print("Datos originales:\n", data)
print("\nDatos normalizados:\n", data_scaled)

Datos originales:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Datos normalizados:
 [[0.26726124 0.53452248 0.80178373]
 [0.45584231 0.56980288 0.68376346]
 [0.50257071 0.57436653 0.64616234]]
